kLearningRate = 0.0005
kNumStickers = 24
kNumCubes = 8
kModelPath = "./model.cpkt"
kMCTSExploration = 4 #this is form alphago, can't dispute it
kDiscountFactor = 1.0
kMCTSSimulateIterations = 250
kLambda = 1.0
kVirtualLoss = 2.0
kNumMinEpochs = 100
kNumMaxEpochs = 1000